### ISSUE TITLE
Oh, so close!

### ISSUE THREAD

**Issue by tslug** [janakaud/aws-cli-repl#1]
I _love_ you for figuring this out, but I'm sadly running on Cygwin for one of my platforms, and it does not support the psutil python module.

I notice you only seem to use one function from it, though, psutil.process_iter().  I don't suppose there might be some way to do this using the os module instead?

**Comment by janakaud** [comment]
@tslug I guess something like this could work: https://stackoverflow.com/questions/2703640/process-list-on-linux-via-python#2704947 - will consider switching the code, whenever I get some time :)

**Comment by gaul** [comment]
Could you try testing with the explicit `AWSR_CLIENT=True` and `AWSR_DAEMON=True` environment values?  This addressed the same symptoms in my Linux environment.

**Comment by tslug** [comment]
> Could you try testing with the explicit `AWSR_CLIENT=True` and `AWSR_DAEMON=True` environment values? This addressed the same symptoms in my Linux environment.

Thanks so much for mentioning, but I've long since moved on from the job where I needed this, and no longer have access to that code base, so I wouldn't have an appropriate testing context for it.

**Comment by gaul** [comment]
Thanks for letting us know!  Let's close this since your symptom is no longer pending.

I think that there are a few paths forward for the auto-forking functionality.  One approach is to drop it entirely and force the user to opt into client or daemon mode.  Another would be to remove the named pipes on daemon exit and the client would check for these on startup (probably good hygiene anyway).  A third approach would be to use a socket and test the port on client startup which would allow multiple clients and perhaps multiple concurrent requests.  I use the explicit mode so let's defer this to some future issue.
